import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { cn } from "@/utils/cn";
import { Navbar } from "@/components/server/Navbar";
import { ReportBar } from "@/components/server/ReportBar";
import { AppQueryProvider } from "@/lib/queryClient";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const montserrat = Montserrat({ subsets: ["latin", "cyrillic"], variable: "--font-montserrat" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="dark">
  <body className={cn("text-base antialiased font-sans", inter.variable, montserrat.variable)}>
    <AppQueryProvider>
      <Navbar />
      <ReportBar />
      {children}
    </AppQueryProvider>
  </body>
    </html>
  );
}
